---
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Updating Ubuntu
    apt:
      name: "*"
      state: latest
  - name: Install tool-kit
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - htop
      - mosh
      - tmux
